# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todobord_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todobord',
            name='image_url',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
